#! /bin/bash

# Install the development version of wok and its dependencies

# clone wok into home
git clone git@github.com:robatron/wok.git $HOME/wok

sudo aptitude install python-pip
sudo pip install PyYAML
sudo pip install jinja2
sudo pip install markdown
